# RUN pre-commit install to set up the pre-commit hooks

# to manually run all pre-commit hooks on a repository: 
# pre-commit run --all-files

# To run individual hooks
# pre-commit run <hook_id>

# Use git commit --no-verify or the shorter form
# git commit -n to skip pre-commit hooks for a
# specific commit. Example:
# git commit -n -m "<git commit msg>"

repos:
- repo: local
  hooks:
    - id: ruff
      name: ruff
      description: "ruff: Python linting"
      entry: ruff check . --fix
      language: python
      types_or: [python]
      require_serial: true
    - id: ruff-format
      name: ruff-format
      description: "ruff: Python formatting"
      entry: ruff format .
      language: python
      types_or: [python]
      require_serial: true
    - id: pytest
      name: pytest
      description: "Run pytest on Python files"
      entry: pytest
      language: python
      types_or: [python]
      pass_filenames: false
      always_run: true
